APP_PREFIX = "cache-commerce"
PRODUCT_CACHE_TTL_SECONDS = 300

CACHE_KEYS = {
  "products": f"{APP_PREFIX}:products:v2"
}

PRODUCTS = [
  {
    "id": "pulse-headphones",
    "name": "Pulse Wireless Headphones",
    "description": "Noise-softening over-ear audio with 40 hours of battery.",
    "pricePaise": 100,
    "badge": "Audio",
    "category": "Electronics",
    "rating": "4.8",
    "stock": 64,
    "delivery": "Same day",
    "channel": "Warehouse",
    "sku": "SM-1001",
    "featured": True,
    "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80",
    "alt": "Black wireless headphones on a bright background"
  },
  {
    "id": "loop-smartwatch",
    "name": "Loop Smart Watch",
    "description": "Lightweight fitness tracking with calls, steps and sleep insights.",
    "pricePaise": 200,
    "badge": "Wearable",
    "category": "Electronics",
    "rating": "4.7",
    "stock": 72,
    "delivery": "2 day",
    "channel": "Marketplace",
    "sku": "SM-1002",
    "featured": True,
    "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",
    "alt": "Smart watch with a clean strap on a tabletop"
  },
  {
    "id": "city-backpack",
    "name": "City Day Backpack",
    "description": "Water-resistant daily bag with a padded laptop section.",
    "pricePaise": 100,
    "badge": "Travel",
    "category": "Bags",
    "rating": "4.5",
    "stock": 51,
    "delivery": "Same day",
    "channel": "Warehouse",
    "sku": "SM-2001",
    "featured": True,
    "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80",
    "alt": "Brown backpack photographed in natural light"
  },
  {
    "id": "nova-sneakers",
    "name": "Nova Run Sneakers",
    "description": "Cushioned everyday sneakers with breathable knit support.",
    "pricePaise": 200,
    "badge": "Footwear",
    "category": "Footwear",
    "rating": "4.6",
    "stock": 86,
    "delivery": "2 day",
    "channel": "Warehouse",
    "sku": "SM-3001",
    "featured": True,
    "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
    "alt": "Red running shoes floating above a red surface"
  },
  {
    "id": "arc-keyboard",
    "name": "Arc Mechanical Keyboard",
    "description": "Compact hot-swap keyboard with quiet tactile switches.",
    "pricePaise": 200,
    "badge": "Workstation",
    "category": "Electronics",
    "rating": "4.9",
    "stock": 43,
    "delivery": "Same day",
    "channel": "Warehouse",
    "sku": "SM-1003",
    "featured": False,
    "image": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80",
    "alt": "Mechanical keyboard on a desk"
  },
  {
    "id": "halo-desk-lamp",
    "name": "Halo Desk Lamp",
    "description": "Dimmable LED desk lamp with wireless phone charging base.",
    "pricePaise": 100,
    "badge": "Home",
    "category": "Home",
    "rating": "4.4",
    "stock": 38,
    "delivery": "2 day",
    "channel": "Marketplace",
    "sku": "SM-4001",
    "featured": False,
    "image": "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80",
    "alt": "Modern desk lamp glowing on a table"
  },
  {
    "id": "terra-bottle",
    "name": "Terra Steel Bottle",
    "description": "Insulated stainless bottle that keeps drinks cold for 24 hours.",
    "pricePaise": 100,
    "badge": "Hydration",
    "category": "Lifestyle",
    "rating": "4.3",
    "stock": 97,
    "delivery": "Same day",
    "channel": "Warehouse",
    "sku": "SM-5001",
    "featured": False,
    "image": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=80",
    "alt": "Reusable steel water bottle"
  },
  {
    "id": "aero-jacket",
    "name": "Aero Rain Jacket",
    "description": "Packable rain shell with taped seams and breathable lining.",
    "pricePaise": 200,
    "badge": "Outerwear",
    "category": "Fashion",
    "rating": "4.5",
    "stock": 45,
    "delivery": "2 day",
    "channel": "Marketplace",
    "sku": "SM-6001",
    "featured": False,
    "image": "https://images.unsplash.com/photo-1548126032-079a0fb0099d?auto=format&fit=crop&w=900&q=80",
    "alt": "Neutral rain jacket hanging on a rack"
  },
  {
    "id": "linen-organizer",
    "name": "Linen Desk Organizer",
    "description": "Modular trays for stationery, cables, notes, and daily carry.",
    "pricePaise": 100,
    "badge": "Office",
    "category": "Home",
    "rating": "4.2",
    "stock": 61,
    "delivery": "Same day",
    "channel": "Warehouse",
    "sku": "SM-4002",
    "featured": False,
    "image": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=900&q=80",
    "alt": "Organized desk with stationery and storage trays"
  },
  {
    "id": "trail-duffel",
    "name": "Trail Weekender Duffel",
    "description": "Carry-on duffel with shoe garage and quick-access pockets.",
    "pricePaise": 200,
    "badge": "Travel",
    "category": "Bags",
    "rating": "4.6",
    "stock": 33,
    "delivery": "2 day",
    "channel": "Warehouse",
    "sku": "SM-2002",
    "featured": False,
    "image": "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=80",
    "alt": "Travel duffel bag on a floor"
  },
  {
    "id": "stride-sandals",
    "name": "Stride Everyday Sandals",
    "description": "Soft footbed sandals with adjustable recycled webbing straps.",
    "pricePaise": 100,
    "badge": "Footwear",
    "category": "Footwear",
    "rating": "4.1",
    "stock": 79,
    "delivery": "Same day",
    "channel": "Marketplace",
    "sku": "SM-3002",
    "featured": False,
    "image": "https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=900&q=80",
    "alt": "Casual sandals on a clean background"
  },
  {
    "id": "muse-speaker",
    "name": "Muse Portable Speaker",
    "description": "Compact waterproof speaker with stereo pairing and punchy bass.",
    "pricePaise": 200,
    "badge": "Audio",
    "category": "Electronics",
    "rating": "4.7",
    "stock": 58,
    "delivery": "Same day",
    "channel": "Warehouse",
    "sku": "SM-1004",
    "featured": False,
    "image": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80",
    "alt": "Portable speaker on a table"
  }
]


def find_product(product_id: str) -> dict | None:
  return next((product for product in PRODUCTS if product["id"] == product_id), None)
